### Signup
POST http://localhost:3000/signup
Content-Type: application/json

{
  "username": "lokeshganni",
  "password": "lokesh123"
}

### Login
POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "lokesh",
  "password": "lokesh123"
}

### POST a Transaction
POST http://localhost:3000/transactions
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imxva2VzaCIsImlhdCI6MTcyOTYyMTYxM30.JFMSnsv1N8uH3d1QTRbmRYnNmGAMkPKdPhQ9vlpMUtE

{
  "type": "income",
  "category": "salary",
  "amount": 5000,
  "date": "2024-10-01",
  "description": "October salary"
}

### GET Paginated Transactions 
GET http://localhost:3000/transactions?page=1&limit=10
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imxva2VzaCIsImlhdCI6MTcyOTYyMTYxM30.JFMSnsv1N8uH3d1QTRbmRYnNmGAMkPKdPhQ9vlpMUtE

### GET Particular Transaction by ID
GET http://localhost:3000/transactions/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imxva2VzaCIsImlhdCI6MTcyOTYyMTYxM30.JFMSnsv1N8uH3d1QTRbmRYnNmGAMkPKdPhQ9vlpMUtE

### PUT Particular Transaction by ID
PUT http://localhost:3000/transactions/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imxva2VzaCIsImlhdCI6MTcyOTYyMTYxM30.JFMSnsv1N8uH3d1QTRbmRYnNmGAMkPKdPhQ9vlpMUtE

{
  "type": "expense",
  "category": "groceries",
  "amount": 300,
  "date": "2024-10-02",
  "description": "Groceries shopping"
}

### DELETE Particular Transaction by ID
DELETE http://localhost:3000/transactions/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imxva2VzaCIsImlhdCI6MTcyOTYyMTYxM30.JFMSnsv1N8uH3d1QTRbmRYnNmGAMkPKdPhQ9vlpMUtE

### GET Transaction Summary
GET http://localhost:3000/summary
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imxva2VzaCIsImlhdCI6MTcyOTYyMTYxM30.JFMSnsv1N8uH3d1QTRbmRYnNmGAMkPKdPhQ9vlpMUtE

### GET Transaction Summary within date range
GET http://localhost:3000/summary?start_date=2024-10-01&end_date=2024-10-31
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imxva2VzaCIsImlhdCI6MTcyOTYyMTYxM30.JFMSnsv1N8uH3d1QTRbmRYnNmGAMkPKdPhQ9vlpMUtE

### GET Transaction Summary filtered by category
GET http://localhost:3000/summary?category=groceries
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imxva2VzaCIsImlhdCI6MTcyOTYyMTYxM30.JFMSnsv1N8uH3d1QTRbmRYnNmGAMkPKdPhQ9vlpMUtE

### GET Monthly Reports
GET http://localhost:3000/reports?month=10&year=2024
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imxva2VzaCIsImlhdCI6MTcyOTYyMTYxM30.JFMSnsv1N8uH3d1QTRbmRYnNmGAMkPKdPhQ9vlpMUtE
